name: Wetter Predictor (Build, Deploy)
# Requires GitHub Action Secrets: AZURE_WEBAPP_NAME, AZURE_WEBAPP_PUBLISH_PROFILE, MONGODB_URI
# Requires Azure Env Variable: AZURE_STORAGE_CONNECTION_STRING, MONGODB_URI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Wetter Predictor (Update Model)"]
    types:
      - completed

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Lowercase the repo name and username
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Build and push container image to registry
      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Lowercase the repo name and username
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}''