name: Wetter Predictor (Update Model)
# Requires GitHub Action Secrets: AZURE_STORAGE_CONNECTION_STRING

on:
  workflow_dispatch:

jobs:
  model:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content
      - name: Checkout repo content
        uses: actions/checkout@v4

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      # Install Python packages
      - name: Install Python packages
        run: pip install -r requirements.txt

      # Run train_model.py to train the model and generate predictions
      - name: Train the model and predict
        run: python model/train_model.py --days-ahead 1  # Default to 1 day ahead

      # Upload models and predictions to Azure Blob Storage
      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          cd model
          python save.py -c "$AZURE_STORAGE_CONNECTION_STRING"